version: '3.7'

volumes: 
  postgres-data:

services: 
  postgres-db:
    image: postgres:13-alpine
    ports:
      - 54321:5432
    env_file:
      - ./clicky/.env
    volumes: 
      - postgres-data:/var/lib/postgresql/data/

  redis:
    image: redis:6-alpine
    ports: 
      - 63791:6379
