version: '3.7'

volumes: 
  postgres-data:
  django-app-static-data:

services: 
  postgres-db:
    image: postgres:13-alpine
    ports:
      - 54321:5432
    env_file:
      - ./clicky/.env
    volumes: 
      - postgres-data:/var/lib/postgresql/data/

  redis:
    image: redis:6-alpine
    ports: 
      - 63791:6379

  django-app:
    build: .
    working_dir: /clicky
    ports:
      - 8000:8000
      - 8001:8001
    depends_on:
      - postgres-db
      - redis
    env_file:
      - ./clicky/.env
    command:
      - sh
      - -c
      - |
        ./../wait
        python manage.py collectstatic --noinput
        python manage.py migrate
        daphne -b 0.0.0.0 -p 8001 config.asgi:application
    volumes:
      - ./clicky:/clicky
      - django-app-static-data:/clicky/static/static_root

  nginx:
    image: nginx:1.19.0-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./clicky/static:/home/app/static/
      - django-app-static-data:/home/app/static/static_root
    ports:
      - 80:80
      - 1337:80
    depends_on:
      - django-app
